### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by nmattia** [kosmikus/records-sop#1]
I understand `records-sop` is currently just an experiment, as mentioned [here](https://github.com/well-typed/generics-sop/issues/8). However I've used it and it greatly simplified the implementation of a new a functionality in [this](https://github.com/dackerman/reflex-jsx) project. Nothing is merged yet though because the project is not mine and I don't want to author to have to deal with "wild" dependencies. Any chance `records-sop` will get release as is (or something close) in the near future?

**Comment by kosmikus** [comment]
Having users is certainly a motivation. Thank you for letting me know.

**Comment by kosmikus** [comment]
@nmattia Current plan is to release generics-sop-0.3 with type-level metadata sometime within the upcoming week, and then I can release records-sop as well.

**Comment by kosmikus** [comment]
Ok, finally all done: https://hackage.haskell.org/package/records-sop-0.1.0.0
