### ISSUE TITLE
Relax ghc-prim up to hackage?

### ISSUE THREAD

**Issue by philderbeast** [kosmikus/records-sop#12]
Would it be possible to upload a new version to hackage with dac554ea3aa18b465ab59c8f0567ca978b94064d?

**Comment by jship** [comment]
https://github.com/kosmikus/records-sop/pull/10 relaxed the upper bound of `ghc-prim` to 0.9. Using the repo's commit abab99b4b870fce55e81dd03d4e41fb50502ca4e (which includes the `ghc-prim` bump) works great for me with GHC 9.2.4. I would second a Hackage release with the latest.

**Comment by jship** [comment]
Gentle bump on this issue. Could a new version be uploaded to Hackage?

**Comment by kosmikus** [comment]
Sorry for the long delays. https://hackage.haskell.org/package/records-sop-0.1.1.1

**Comment by philderbeast** [comment]
Thanks for the release @kosmikus.
